"""baseline schema

Revision ID: f09ff51e3cde
Revises: 
Create Date: 2026-08-13 11:02:05.741930
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f09ff51e3cde'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tagline', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('prize_pool', sa.Float(), nullable=True),
    sa.Column('prizes', sa.Text(), nullable=True),
    sa.Column('rules', sa.Text(), nullable=True),
    sa.Column('max_participants', sa.Integer(), nullable=True),
    sa.Column('entry_fee', sa.Float(), nullable=True),
    sa.Column('registration_end', sa.DateTime(), nullable=True),
    sa.Column('starting_capital', sa.Float(), nullable=True),
    sa.Column('winners', sa.Text(), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenges_id'), 'challenges', ['id'], unique=False)
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('sector', sa.Enum('BANQUE', 'ASSURANCE', 'AGROALIMENTAIRE', 'DISTRIBUTION', 'TRANSPORT', 'TELECOMS', 'PETROLIER', 'SERVICES_PUBLICS', 'MATERIAUX', 'IMMOBILIER', 'HOLDING', 'SERVICES_FINANCIERS', 'CONSOMMATION_BASE', 'CONSOMMATION_DISCRETIONNAIRE', 'ENERGIE', 'INDUSTRIELS', 'AUTRE', name='sector'), nullable=False),
    sa.Column('instrument_type', sa.String(length=20), server_default='equity', nullable=False),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('isin', sa.String(length=20), nullable=True),
    sa.Column('listing_date', sa.DateTime(), nullable=True),
    sa.Column('shares_outstanding', sa.Float(), nullable=True),
    sa.Column('per', sa.Float(), nullable=True),
    sa.Column('reference_price', sa.Float(), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('isin')
    )
    op.create_index(op.f('ix_companies_id'), 'companies', ['id'], unique=False)
    op.create_index(op.f('ix_companies_symbol'), 'companies', ['symbol'], unique=True)
    op.create_table('kyc_webhook_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_event_id', sa.String(), nullable=False),
    sa.Column('provider_session_id', sa.String(), nullable=False),
    sa.Column('vendor_data', sa.String(), nullable=True),
    sa.Column('webhook_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_webhook_events_id'), 'kyc_webhook_events', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_webhook_events_provider_event_id'), 'kyc_webhook_events', ['provider_event_id'], unique=True)
    op.create_index(op.f('ix_kyc_webhook_events_provider_session_id'), 'kyc_webhook_events', ['provider_session_id'], unique=False)
    op.create_index(op.f('ix_kyc_webhook_events_vendor_data'), 'kyc_webhook_events', ['vendor_data'], unique=False)
    op.create_table('macro_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.String(length=50), nullable=False),
    sa.Column('indicator', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('indicator', 'date', name='uq_macro_indicator_date')
    )
    op.create_index(op.f('ix_macro_indicators_date'), 'macro_indicators', ['date'], unique=False)
    op.create_index(op.f('ix_macro_indicators_id'), 'macro_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_macro_indicators_indicator'), 'macro_indicators', ['indicator'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auth_id', sa.UUID(), nullable=True),
    sa.Column('legacy_hash', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('broker_account', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('email_notif_enabled', sa.Boolean(), nullable=False),
    sa.Column('api_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verify_code', sa.String(), nullable=True),
    sa.Column('email_verify_expires', sa.DateTime(), nullable=True),
    sa.Column('email_verify_attempts', sa.Integer(), nullable=False),
    sa.Column('email_verify_sent_at', sa.DateTime(), nullable=True),
    sa.Column('totp_secret', sa.String(), nullable=True),
    sa.Column('totp_enabled', sa.Boolean(), nullable=False),
    sa.Column('recovery_codes', sa.String(), nullable=True),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_reset_code', sa.String(), nullable=True),
    sa.Column('password_reset_expires', sa.DateTime(), nullable=True),
    sa.Column('password_reset_attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_api_token'), 'users', ['api_token'], unique=True)
    op.create_index(op.f('ix_users_auth_id'), 'users', ['auth_id'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('report_type', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('raw_analysis', sa.JSON(), nullable=True),
    sa.Column('recommendations', sa.String(length=50), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_reports_id'), 'analysis_reports', ['id'], unique=False)
    op.create_table('broker_client_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('account_number', sa.String(), nullable=False),
    sa.Column('holder_name', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('holdings', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('linked_user_id', sa.Integer(), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['linked_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_client_accounts_account_number'), 'broker_client_accounts', ['account_number'], unique=True)
    op.create_index(op.f('ix_broker_client_accounts_broker_name'), 'broker_client_accounts', ['broker_name'], unique=False)
    op.create_index(op.f('ix_broker_client_accounts_id'), 'broker_client_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_broker_client_accounts_linked_user_id'), 'broker_client_accounts', ['linked_user_id'], unique=False)
    op.create_table('challenge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('challenge_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=True),
    sa.Column('joined_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('challenge_id', 'user_id', name='uq_challenge_entry')
    )
    op.create_index(op.f('ix_challenge_entries_challenge_id'), 'challenge_entries', ['challenge_id'], unique=False)
    op.create_index(op.f('ix_challenge_entries_id'), 'challenge_entries', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_entries_user_id'), 'challenge_entries', ['user_id'], unique=False)
    op.create_table('community_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('handle', sa.String(length=40), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('bio', sa.String(length=400), nullable=True),
    sa.Column('avatar_color', sa.String(length=7), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_users_handle'), 'community_users', ['handle'], unique=True)
    op.create_index(op.f('ix_community_users_id'), 'community_users', ['id'], unique=False)
    op.create_index(op.f('ix_community_users_user_id'), 'community_users', ['user_id'], unique=False)
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('dividend_per_share', sa.Float(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=True),
    sa.Column('payment_date', sa.Date(), nullable=True),
    sa.Column('dividend_type', sa.String(length=50), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'fiscal_year', name='uq_dividends_company_year')
    )
    op.create_index(op.f('ix_dividends_id'), 'dividends', ['id'], unique=False)
    op.create_table('financial_ratios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roa', sa.Float(), nullable=True),
    sa.Column('net_margin', sa.Float(), nullable=True),
    sa.Column('operating_margin', sa.Float(), nullable=True),
    sa.Column('gross_margin', sa.Float(), nullable=True),
    sa.Column('ebitda_margin', sa.Float(), nullable=True),
    sa.Column('cost_to_income', sa.Float(), nullable=True),
    sa.Column('asset_turnover', sa.Float(), nullable=True),
    sa.Column('inventory_turnover', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('quick_ratio', sa.Float(), nullable=True),
    sa.Column('cash_ratio', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('debt_to_assets', sa.Float(), nullable=True),
    sa.Column('interest_coverage', sa.Float(), nullable=True),
    sa.Column('revenue_growth', sa.Float(), nullable=True),
    sa.Column('net_income_growth', sa.Float(), nullable=True),
    sa.Column('eps_growth', sa.Float(), nullable=True),
    sa.Column('book_value_growth', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('bvps', sa.Float(), nullable=True),
    sa.Column('cfps', sa.Float(), nullable=True),
    sa.Column('fcf_per_share', sa.Float(), nullable=True),
    sa.Column('dividend_per_share', sa.Float(), nullable=True),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('ps_ratio', sa.Float(), nullable=True),
    sa.Column('ev_ebitda', sa.Float(), nullable=True),
    sa.Column('ev_ebit', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.Column('payout_ratio', sa.Float(), nullable=True),
    sa.Column('loan_to_deposit', sa.Float(), nullable=True),
    sa.Column('cost_of_risk', sa.Float(), nullable=True),
    sa.Column('net_interest_margin', sa.Float(), nullable=True),
    sa.Column('tier1_capital_ratio', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_ratios_id'), 'financial_ratios', ['id'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('statement_type', sa.Enum('INCOME', 'BALANCE', 'CASH_FLOW', 'NOTES', name='statementtype'), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('source_file', sa.String(length=500), nullable=True),
    sa.Column('is_consolidated', sa.Boolean(), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_statements_company_id'), 'financial_statements', ['company_id'], unique=False)
    op.create_index(op.f('ix_financial_statements_id'), 'financial_statements', ['id'], unique=False)
    op.create_table('market_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open_price', sa.Float(), nullable=True),
    sa.Column('high_price', sa.Float(), nullable=True),
    sa.Column('low_price', sa.Float(), nullable=True),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.Column('change_percent', sa.Float(), nullable=True),
    sa.Column('market_cap', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('is_synthetic', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'date', name='uq_market_data_company_date')
    )
    op.create_index(op.f('ix_market_data_company_id'), 'market_data', ['company_id'], unique=False)
    op.create_index(op.f('ix_market_data_date'), 'market_data', ['date'], unique=False)
    op.create_index(op.f('ix_market_data_id'), 'market_data', ['id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('link', sa.String(length=200), nullable=True),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('email_sent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('scorecards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('profitability_score', sa.Float(), nullable=True),
    sa.Column('growth_score', sa.Float(), nullable=True),
    sa.Column('debt_score', sa.Float(), nullable=True),
    sa.Column('liquidity_score', sa.Float(), nullable=True),
    sa.Column('management_score', sa.Float(), nullable=True),
    sa.Column('valuation_score', sa.Float(), nullable=True),
    sa.Column('moat_score', sa.Float(), nullable=True),
    sa.Column('momentum_score', sa.Float(), nullable=True),
    sa.Column('total_score', sa.Float(), nullable=True),
    sa.Column('rating', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scorecards_id'), 'scorecards', ['id'], unique=False)
    op.create_table('user_kyc',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('review_note', sa.Text(), nullable=True),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.Column('civility', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('birth_place', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.Column('marital_status', sa.String(), nullable=True),
    sa.Column('nif', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('company_rc', sa.String(), nullable=True),
    sa.Column('company_nif', sa.String(), nullable=True),
    sa.Column('id_type', sa.String(), nullable=True),
    sa.Column('id_number', sa.String(), nullable=True),
    sa.Column('id_issue_date', sa.String(), nullable=True),
    sa.Column('id_expiry_date', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('profession', sa.String(), nullable=True),
    sa.Column('employer', sa.String(), nullable=True),
    sa.Column('monthly_income', sa.String(), nullable=True),
    sa.Column('source_of_funds', sa.String(), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('tax_residence', sa.String(), nullable=True),
    sa.Column('invest_experience', sa.String(), nullable=True),
    sa.Column('invest_objectives', sa.String(), nullable=True),
    sa.Column('invest_knowledge', sa.String(), nullable=True),
    sa.Column('risk_tolerance', sa.String(), nullable=True),
    sa.Column('invest_horizon', sa.String(), nullable=True),
    sa.Column('signature_name', sa.String(), nullable=True),
    sa.Column('consent', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_kyc_id'), 'user_kyc', ['id'], unique=False)
    op.create_index(op.f('ix_user_kyc_user_id'), 'user_kyc', ['user_id'], unique=True)
    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year', sa.Integer(), nullable=False),
    sa.Column('dcf_value', sa.Float(), nullable=True),
    sa.Column('dcf_assumptions', sa.JSON(), nullable=True),
    sa.Column('graham_value', sa.Float(), nullable=True),
    sa.Column('buffett_value', sa.Float(), nullable=True),
    sa.Column('ev_ebitda_value', sa.Float(), nullable=True),
    sa.Column('ev_ebit_value', sa.Float(), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('discount_percent', sa.Float(), nullable=True),
    sa.Column('recommendation', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_valuations_id'), 'valuations', ['id'], unique=False)
    op.create_table('broker_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=False),
    sa.Column('broker_category', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('id_type', sa.String(), nullable=False),
    sa.Column('id_number', sa.String(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('sgi_note', sa.Text(), nullable=True),
    sa.Column('user_response', sa.Text(), nullable=True),
    sa.Column('transmitted_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('account_opened_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['user_kyc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_accounts_id'), 'broker_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_broker_accounts_kyc_id'), 'broker_accounts', ['kyc_id'], unique=False)
    op.create_index(op.f('ix_broker_accounts_user_id'), 'broker_accounts', ['user_id'], unique=False)
    op.create_table('broker_login_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=True),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('account_number', sa.String(), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['broker_client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_login_events_client_account_id'), 'broker_login_events', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_broker_login_events_id'), 'broker_login_events', ['id'], unique=False)
    op.create_table('broker_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_account_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_account_id'], ['broker_client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_broker_sessions_client_account_id'), 'broker_sessions', ['client_account_id'], unique=False)
    op.create_index(op.f('ix_broker_sessions_id'), 'broker_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_broker_sessions_token_hash'), 'broker_sessions', ['token_hash'], unique=True)
    op.create_table('challenge_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('cash', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['challenge_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', name='uq_challenge_portfolio_entry')
    )
    op.create_index(op.f('ix_challenge_portfolios_entry_id'), 'challenge_portfolios', ['entry_id'], unique=False)
    op.create_index(op.f('ix_challenge_portfolios_id'), 'challenge_portfolios', ['id'], unique=False)
    op.create_table('challenge_value_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['entry_id'], ['challenge_entries.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entry_id', 'day', name='uq_challenge_snapshot')
    )
    op.create_index(op.f('ix_challenge_value_snapshots_day'), 'challenge_value_snapshots', ['day'], unique=False)
    op.create_index(op.f('ix_challenge_value_snapshots_entry_id'), 'challenge_value_snapshots', ['entry_id'], unique=False)
    op.create_index(op.f('ix_challenge_value_snapshots_id'), 'challenge_value_snapshots', ['id'], unique=False)
    op.create_table('community_follows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['community_users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['community_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('follower_id', 'followed_id', name='uq_follow_pair')
    )
    op.create_index(op.f('ix_community_follows_followed_id'), 'community_follows', ['followed_id'], unique=False)
    op.create_index(op.f('ix_community_follows_follower_id'), 'community_follows', ['follower_id'], unique=False)
    op.create_index(op.f('ix_community_follows_id'), 'community_follows', ['id'], unique=False)
    op.create_table('community_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('sentiment', sa.String(length=10), nullable=True),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('is_editor_pick', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['community_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_posts_author_id'), 'community_posts', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_posts_id'), 'community_posts', ['id'], unique=False)
    op.create_index(op.f('ix_community_posts_symbol'), 'community_posts', ['symbol'], unique=False)
    op.create_table('financial_line_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=True),
    sa.Column('account_name', sa.String(length=200), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('note_reference', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['statement_id'], ['financial_statements.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_line_items_id'), 'financial_line_items', ['id'], unique=False)
    op.create_table('kyc_documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.String(), nullable=False),
    sa.Column('original_name', sa.String(), nullable=False),
    sa.Column('stored_name', sa.String(), nullable=False),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['user_kyc.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_documents_doc_type'), 'kyc_documents', ['doc_type'], unique=False)
    op.create_index(op.f('ix_kyc_documents_id'), 'kyc_documents', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_documents_kyc_id'), 'kyc_documents', ['kyc_id'], unique=False)
    op.create_table('kyc_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kyc_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_session_id', sa.String(), nullable=False),
    sa.Column('vendor_data', sa.String(), nullable=False),
    sa.Column('session_status', sa.String(), nullable=True),
    sa.Column('verification_url', sa.String(), nullable=True),
    sa.Column('decision', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kyc_id'], ['user_kyc.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_verifications_id'), 'kyc_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_kyc_verifications_kyc_id'), 'kyc_verifications', ['kyc_id'], unique=False)
    op.create_index(op.f('ix_kyc_verifications_provider_session_id'), 'kyc_verifications', ['provider_session_id'], unique=True)
    op.create_index(op.f('ix_kyc_verifications_user_id'), 'kyc_verifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_kyc_verifications_vendor_data'), 'kyc_verifications', ['vendor_data'], unique=False)
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('broker_name', sa.String(), nullable=True),
    sa.Column('broker_client_id', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['broker_client_id'], ['broker_client_accounts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolios_broker_client_id'), 'portfolios', ['broker_client_id'], unique=False)
    op.create_index(op.f('ix_portfolios_id'), 'portfolios', ['id'], unique=False)
    op.create_table('challenge_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('avg_price', sa.Float(), nullable=False),
    sa.Column('current_price', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['challenge_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'symbol', name='uq_challenge_position')
    )
    op.create_index(op.f('ix_challenge_positions_id'), 'challenge_positions', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_positions_portfolio_id'), 'challenge_positions', ['portfolio_id'], unique=False)
    op.create_table('challenge_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['challenge_portfolios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_challenge_trades_id'), 'challenge_trades', ['id'], unique=False)
    op.create_index(op.f('ix_challenge_trades_portfolio_id'), 'challenge_trades', ['portfolio_id'], unique=False)
    op.create_table('community_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=600), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['community_users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_community_comments_author_id'), 'community_comments', ['author_id'], unique=False)
    op.create_index(op.f('ix_community_comments_id'), 'community_comments', ['id'], unique=False)
    op.create_index(op.f('ix_community_comments_post_id'), 'community_comments', ['post_id'], unique=False)
    op.create_table('community_reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['community_posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['community_users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'user_id', name='uq_post_reaction')
    )
    op.create_index(op.f('ix_community_reactions_id'), 'community_reactions', ['id'], unique=False)
    op.create_index(op.f('ix_community_reactions_post_id'), 'community_reactions', ['post_id'], unique=False)
    op.create_index(op.f('ix_community_reactions_user_id'), 'community_reactions', ['user_id'], unique=False)
    op.create_table('deposit_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('provider_transaction_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('credited', sa.Boolean(), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_orders_id'), 'deposit_orders', ['id'], unique=False)
    op.create_index(op.f('ix_deposit_orders_portfolio_id'), 'deposit_orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_deposit_orders_provider_transaction_id'), 'deposit_orders', ['provider_transaction_id'], unique=True)
    op.create_index(op.f('ix_deposit_orders_user_id'), 'deposit_orders', ['user_id'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=True),
    sa.Column('avg_price', sa.Float(), nullable=True),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_id'), 'positions', ['id'], unique=False)
    op.create_index(op.f('ix_positions_portfolio_id'), 'positions', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_index(op.f('ix_positions_user_id'), 'positions', ['user_id'], unique=False)
    op.create_table('premium_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('monthly', sa.Float(), nullable=False),
    sa.Column('horizon_years', sa.Integer(), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('plan_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('matured_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('linked_to_portfolio', sa.Boolean(), nullable=False),
    sa.Column('linked_at', sa.DateTime(), nullable=True),
    sa.Column('managed_portfolio_id', sa.Integer(), nullable=True),
    sa.Column('pin_hash', sa.String(), nullable=True),
    sa.Column('allocation_snapshot', sa.Text(), nullable=True),
    sa.Column('start_value', sa.Float(), nullable=True),
    sa.Column('last_value', sa.Float(), nullable=True),
    sa.Column('last_pnl_pct', sa.Float(), nullable=True),
    sa.Column('last_tracked_at', sa.DateTime(), nullable=True),
    sa.Column('last_day_change_pct', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['managed_portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_plans_id'), 'premium_plans', ['id'], unique=False)
    op.create_index(op.f('ix_premium_plans_user_id'), 'premium_plans', ['user_id'], unique=False)
    op.create_table('user_portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('is_owner', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_portfolios_id'), 'user_portfolios', ['id'], unique=False)
    op.create_index(op.f('ix_user_portfolios_portfolio_id'), 'user_portfolios', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_user_portfolios_user_id'), 'user_portfolios', ['user_id'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(), nullable=False),
    sa.Column('side', sa.String(), nullable=False),
    sa.Column('qty', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('order_type', sa.String(), nullable=False),
    sa.Column('limit_price', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('take_profit', sa.Float(), nullable=True),
    sa.Column('stop_loss', sa.Float(), nullable=True),
    sa.Column('plan_id', sa.Integer(), nullable=True),
    sa.Column('broker_ref', sa.String(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['premium_plans.id'], ),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_broker_ref'), 'orders', ['broker_ref'], unique=False)
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_index(op.f('ix_orders_plan_id'), 'orders', ['plan_id'], unique=False)
    op.create_index(op.f('ix_orders_portfolio_id'), 'orders', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.create_table('premium_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plan_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('invested', sa.Float(), nullable=False),
    sa.Column('pnl_pct', sa.Float(), nullable=False),
    sa.Column('day_change_pct', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['premium_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_premium_snapshots_date'), 'premium_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_premium_snapshots_id'), 'premium_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_premium_snapshots_plan_id'), 'premium_snapshots', ['plan_id'], unique=False)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_premium_snapshots_plan_id'), table_name='premium_snapshots')
    op.drop_index(op.f('ix_premium_snapshots_id'), table_name='premium_snapshots')
    op.drop_index(op.f('ix_premium_snapshots_date'), table_name='premium_snapshots')
    op.drop_table('premium_snapshots')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_portfolio_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_plan_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_broker_ref'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_user_portfolios_user_id'), table_name='user_portfolios')
    op.drop_index(op.f('ix_user_portfolios_portfolio_id'), table_name='user_portfolios')
    op.drop_index(op.f('ix_user_portfolios_id'), table_name='user_portfolios')
    op.drop_table('user_portfolios')
    op.drop_index(op.f('ix_premium_plans_user_id'), table_name='premium_plans')
    op.drop_index(op.f('ix_premium_plans_id'), table_name='premium_plans')
    op.drop_table('premium_plans')
    op.drop_index(op.f('ix_positions_user_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_index(op.f('ix_positions_portfolio_id'), table_name='positions')
    op.drop_index(op.f('ix_positions_id'), table_name='positions')
    op.drop_table('positions')
    op.drop_index(op.f('ix_deposit_orders_user_id'), table_name='deposit_orders')
    op.drop_index(op.f('ix_deposit_orders_provider_transaction_id'), table_name='deposit_orders')
    op.drop_index(op.f('ix_deposit_orders_portfolio_id'), table_name='deposit_orders')
    op.drop_index(op.f('ix_deposit_orders_id'), table_name='deposit_orders')
    op.drop_table('deposit_orders')
    op.drop_index(op.f('ix_community_reactions_user_id'), table_name='community_reactions')
    op.drop_index(op.f('ix_community_reactions_post_id'), table_name='community_reactions')
    op.drop_index(op.f('ix_community_reactions_id'), table_name='community_reactions')
    op.drop_table('community_reactions')
    op.drop_index(op.f('ix_community_comments_post_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_id'), table_name='community_comments')
    op.drop_index(op.f('ix_community_comments_author_id'), table_name='community_comments')
    op.drop_table('community_comments')
    op.drop_index(op.f('ix_challenge_trades_portfolio_id'), table_name='challenge_trades')
    op.drop_index(op.f('ix_challenge_trades_id'), table_name='challenge_trades')
    op.drop_table('challenge_trades')
    op.drop_index(op.f('ix_challenge_positions_portfolio_id'), table_name='challenge_positions')
    op.drop_index(op.f('ix_challenge_positions_id'), table_name='challenge_positions')
    op.drop_table('challenge_positions')
    op.drop_index(op.f('ix_portfolios_id'), table_name='portfolios')
    op.drop_index(op.f('ix_portfolios_broker_client_id'), table_name='portfolios')
    op.drop_table('portfolios')
    op.drop_index(op.f('ix_kyc_verifications_vendor_data'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_user_id'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_provider_session_id'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_kyc_id'), table_name='kyc_verifications')
    op.drop_index(op.f('ix_kyc_verifications_id'), table_name='kyc_verifications')
    op.drop_table('kyc_verifications')
    op.drop_index(op.f('ix_kyc_documents_kyc_id'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_id'), table_name='kyc_documents')
    op.drop_index(op.f('ix_kyc_documents_doc_type'), table_name='kyc_documents')
    op.drop_table('kyc_documents')
    op.drop_index(op.f('ix_financial_line_items_id'), table_name='financial_line_items')
    op.drop_table('financial_line_items')
    op.drop_index(op.f('ix_community_posts_symbol'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_id'), table_name='community_posts')
    op.drop_index(op.f('ix_community_posts_author_id'), table_name='community_posts')
    op.drop_table('community_posts')
    op.drop_index(op.f('ix_community_follows_id'), table_name='community_follows')
    op.drop_index(op.f('ix_community_follows_follower_id'), table_name='community_follows')
    op.drop_index(op.f('ix_community_follows_followed_id'), table_name='community_follows')
    op.drop_table('community_follows')
    op.drop_index(op.f('ix_challenge_value_snapshots_id'), table_name='challenge_value_snapshots')
    op.drop_index(op.f('ix_challenge_value_snapshots_entry_id'), table_name='challenge_value_snapshots')
    op.drop_index(op.f('ix_challenge_value_snapshots_day'), table_name='challenge_value_snapshots')
    op.drop_table('challenge_value_snapshots')
    op.drop_index(op.f('ix_challenge_portfolios_id'), table_name='challenge_portfolios')
    op.drop_index(op.f('ix_challenge_portfolios_entry_id'), table_name='challenge_portfolios')
    op.drop_table('challenge_portfolios')
    op.drop_index(op.f('ix_broker_sessions_token_hash'), table_name='broker_sessions')
    op.drop_index(op.f('ix_broker_sessions_id'), table_name='broker_sessions')
    op.drop_index(op.f('ix_broker_sessions_client_account_id'), table_name='broker_sessions')
    op.drop_table('broker_sessions')
    op.drop_index(op.f('ix_broker_login_events_id'), table_name='broker_login_events')
    op.drop_index(op.f('ix_broker_login_events_client_account_id'), table_name='broker_login_events')
    op.drop_table('broker_login_events')
    op.drop_index(op.f('ix_broker_accounts_user_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_kyc_id'), table_name='broker_accounts')
    op.drop_index(op.f('ix_broker_accounts_id'), table_name='broker_accounts')
    op.drop_table('broker_accounts')
    op.drop_index(op.f('ix_valuations_id'), table_name='valuations')
    op.drop_table('valuations')
    op.drop_index(op.f('ix_user_kyc_user_id'), table_name='user_kyc')
    op.drop_index(op.f('ix_user_kyc_id'), table_name='user_kyc')
    op.drop_table('user_kyc')
    op.drop_index(op.f('ix_scorecards_id'), table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_market_data_id'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_date'), table_name='market_data')
    op.drop_index(op.f('ix_market_data_company_id'), table_name='market_data')
    op.drop_table('market_data')
    op.drop_index(op.f('ix_financial_statements_id'), table_name='financial_statements')
    op.drop_index(op.f('ix_financial_statements_company_id'), table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index(op.f('ix_financial_ratios_id'), table_name='financial_ratios')
    op.drop_table('financial_ratios')
    op.drop_index(op.f('ix_dividends_id'), table_name='dividends')
    op.drop_table('dividends')
    op.drop_index(op.f('ix_community_users_user_id'), table_name='community_users')
    op.drop_index(op.f('ix_community_users_id'), table_name='community_users')
    op.drop_index(op.f('ix_community_users_handle'), table_name='community_users')
    op.drop_table('community_users')
    op.drop_index(op.f('ix_challenge_entries_user_id'), table_name='challenge_entries')
    op.drop_index(op.f('ix_challenge_entries_id'), table_name='challenge_entries')
    op.drop_index(op.f('ix_challenge_entries_challenge_id'), table_name='challenge_entries')
    op.drop_table('challenge_entries')
    op.drop_index(op.f('ix_broker_client_accounts_linked_user_id'), table_name='broker_client_accounts')
    op.drop_index(op.f('ix_broker_client_accounts_id'), table_name='broker_client_accounts')
    op.drop_index(op.f('ix_broker_client_accounts_broker_name'), table_name='broker_client_accounts')
    op.drop_index(op.f('ix_broker_client_accounts_account_number'), table_name='broker_client_accounts')
    op.drop_table('broker_client_accounts')
    op.drop_index(op.f('ix_analysis_reports_id'), table_name='analysis_reports')
    op.drop_table('analysis_reports')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_auth_id'), table_name='users')
    op.drop_index(op.f('ix_users_api_token'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_macro_indicators_indicator'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_id'), table_name='macro_indicators')
    op.drop_index(op.f('ix_macro_indicators_date'), table_name='macro_indicators')
    op.drop_table('macro_indicators')
    op.drop_index(op.f('ix_kyc_webhook_events_vendor_data'), table_name='kyc_webhook_events')
    op.drop_index(op.f('ix_kyc_webhook_events_provider_session_id'), table_name='kyc_webhook_events')
    op.drop_index(op.f('ix_kyc_webhook_events_provider_event_id'), table_name='kyc_webhook_events')
    op.drop_index(op.f('ix_kyc_webhook_events_id'), table_name='kyc_webhook_events')
    op.drop_table('kyc_webhook_events')
    op.drop_index(op.f('ix_companies_symbol'), table_name='companies')
    op.drop_index(op.f('ix_companies_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_challenges_id'), table_name='challenges')
    op.drop_table('challenges')
    # ### end Alembic commands ###
